# Generated by Django 5.0 on 2024-07-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0077_alter_stateprogram_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusamount',
            name='unlimited',
        ),
    ]
