# Generated by Django 5.0 on 2024-07-22 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0078_remove_bonusamount_unlimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusmaxwin',
            name='unlimited',
        ),
        migrations.AlterField(
            model_name='bonusexpiration',
            name='days',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], help_text='This means that the player has X days to wager his bonus. Otherwise it will be canceled, etc.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Amount of Days'),
        ),
        migrations.AlterField(
            model_name='bonusmindep',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Minimum deposit to active the bonus. Usually around 10 EUR', null=True, verbose_name='Bonus min dep value'),
        ),
        migrations.AlterField(
            model_name='bonusmindep',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_min_dep', to='app_casinos.basecurrency'),
        ),
        migrations.AlterField(
            model_name='bonusvalue',
            name='value',
            field=models.IntegerField(blank=True, help_text="Bonus value in percentage. So, for example if it says '200% up to 200 EUR' then bonus value is 200%", null=True, verbose_name='Value %'),
        ),
        migrations.AlterField(
            model_name='wageringcontribution',
            name='contribution_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagering_contribution', to='app_casinos.wageringcontributionvalue'),
        ),
        migrations.AlterField(
            model_name='wageringcontribution',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wagering Contribution value %'),
        ),
    ]
