# Generated by Django 5.0 on 2024-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0079_remove_bonusmaxwin_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusamount',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonusmaxwin',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
