# Generated by Django 5.0 on 2024-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0080_bonusamount_unlimited_bonusmaxwin_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_only',
            field=models.FloatField(blank=True, help_text='Manually calculate the total bonus amount when wagering applies to bonus only. For instance, if you deposited 100 EUR and received a 100 EUR bonus, the total bonus amount would be 100 EUR.', null=True, verbose_name='Bonus Only'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_plus_deposit',
            field=models.FloatField(blank=True, help_text='Manually calculate the total bonus amount when wagering applies to both the bonus and deposit. For instance, if you deposited 100 EUR and received a 100 EUR bonus, the total bonus amount would be 200 EUR.', null=True, verbose_name='Bonus + Deposit'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_plus_freespins_value',
            field=models.FloatField(blank=True, help_text='Manually calculate the total value of awarded free spins and add the bonus only amount. For example, if you get 50 free spins where each spin is 0.1 EUR then the total value is 5 EUR', null=True, verbose_name='Bonus + Freespins value'),
        ),
        migrations.AlterField(
            model_name='bonusamount',
            name='value',
            field=models.FloatField(blank=True, help_text="The maximum bonus amount that the casino can match. Usually defined defined as: 'up to 200 EUR'", null=True, verbose_name='(CAP) value'),
        ),
        migrations.AlterField(
            model_name='bonusmaxbet',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Bonus Max Bet value'),
        ),
        migrations.AlterField(
            model_name='bonusmaxwin',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Max win is the same as max withdrawal from the bonus.', null=True, verbose_name='Bonus Max Win value'),
        ),
        migrations.AlterField(
            model_name='bonusmindep',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Minimum deposit to active the bonus. Usually around 10 EUR', null=True, verbose_name='Bonus min dep value'),
        ),
        migrations.AlterField(
            model_name='bonusvalue',
            name='value',
            field=models.FloatField(blank=True, help_text="Bonus value in percentage. So, for example if it says '200% up to 200 EUR' then bonus value is 200%", null=True, verbose_name='Value %'),
        ),
        migrations.AlterField(
            model_name='cashback',
            name='wager',
            field=models.FloatField(blank=True, null=True, verbose_name='Wager X'),
        ),
        migrations.AlterField(
            model_name='freespinamount',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Free Spins value'),
        ),
        migrations.AlterField(
            model_name='levelupbonus',
            name='wager',
            field=models.FloatField(blank=True, null=True, verbose_name='Wager'),
        ),
        migrations.AlterField(
            model_name='minwagering',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slotswageringcontribution',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wagering Contribution value %'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wager value'),
        ),
        migrations.AlterField(
            model_name='wageringbonusplusdeposit',
            name='bonus_only',
            field=models.FloatField(blank=True, help_text='Applies if wagering requirements are for bonus only', null=True, verbose_name='(Wagering) Bonus Only'),
        ),
        migrations.AlterField(
            model_name='wageringbonusplusdeposit',
            name='bonus_plus_deposit',
            field=models.FloatField(blank=True, help_text='Applies if wagering requirements are for bonus + deposit', null=True, verbose_name='(Wagering) Bonus + Deposit'),
        ),
        migrations.AlterField(
            model_name='wageringcontribution',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Wagering Contribution value %'),
        ),
    ]
