# Generated by Django 5.0 on 2024-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0081_alter_bonus_bonus_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusmaxbet',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
