# Generated by Django 5.0.7 on 2024-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0082_bonusmaxbet_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Casino Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='casino',
            name='casino_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='casino', to='app_casinos.casinocategory'),
        ),
    ]
