# Generated by Django 5.0.7 on 2024-08-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0083_casinocategory_casino_casino_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='special_promo_category',
            field=models.BooleanField(default=False, verbose_name='Special Promo Category'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='special_side_bar',
            field=models.BooleanField(default=False, verbose_name='Special Side Bar Promo'),
        ),
    ]
