# Generated by Django 5.0.7 on 2024-08-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0085_casino_casino_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='casino_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Casino Likes'),
        ),
        migrations.CreateModel(
            name='LoyaltyKeypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty_keypoint_images/', verbose_name='Loyalty Keypoint Image')),
                ('text_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description 1')),
                ('text_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description 2')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_keypoint', to='app_casinos.loyaltyprogram')),
            ],
        ),
    ]
