# Generated by Django 5.0.7 on 2024-08-01 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0087_licensingauthority_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Payout Speed Value')),
            ],
        ),
        migrations.AddField(
            model_name='casino',
            name='payout_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.payoutspeed'),
        ),
    ]
