# Generated by Django 5.0.7 on 2024-08-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0088_payoutspeed_casino_payout_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutspeed',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='casino',
            name='review',
            field=models.TextField(blank=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='payout_speed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.payoutspeed', verbose_name='Payout Speed'),
        ),
    ]
