# Generated by Django 5.0.7 on 2024-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0090_alter_casinocategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base_casino_images/', verbose_name='Base Casino Image'),
        ),
    ]
