# Generated by Django 5.0.7 on 2024-08-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0092_bonuscategory_label_alter_casino_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Bonus Description'),
        ),
    ]
