# Generated by Django 5.0.7 on 2024-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0093_bonus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bonuses/files/'),
        ),
    ]
