# Generated by Django 5.0.7 on 2024-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0096_loyaltyprogram_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus Likes'),
        ),
    ]
